In [1]:
import numpy as np
import skimage as ski

In [2]:
img = np.arange(36).reshape((6, 6))
img

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [3]:
ski.measure.profile_line(img, [1, 0], [1, 4])

array([ 6.,  7.,  8.,  9., 10.])

In [4]:
ski.measure.profile_line(img, [0, 2], [4, 2])

array([ 2.,  8., 14., 20., 26.])